### ISSUE TITLE
[FEATURE] Support array of ignore list as ignoreFile

### ISSUE THREAD

**Issue by amio** [npm/ignore-walk#12]
# What / Why

For such use cases:
- builtin ignore list, like `['.git']`
- fine control with priority

## Usage Example

```js
const builtinIgnore = ['.git', '!dist']

ignoreWalk({
  ignoreFiles: ['.gitignore', builtinIgnore, '.customignore']
}
```

## Thoughts

- With this we can resolve #2 too, but also support a wider range use cases, like this [hack](https://github.com/athombv/node-homey/pull/20/files#diff-fade80ab9ee854b017bc9cddff7f03eaR676).
- Maybe we need to change the name `ignoreFiles` to something else then, which making it a breaking change.

**Comment by wraithgar** [comment]
Closing this one due to age.
