### ISSUE TITLE
[BUG] Negated patterns cancel all previous folder patterns

### ISSUE THREAD

**Issue by LinqLover** [npm/ignore-walk#17]
Example repository:

```
example
├── bin
│   └── some.thing
├── foo.txt
└── .ignore
```

`.ignore` file:

```ignore
bin/

# The packages folder can be ignored because of Package Restore
**/[Pp]ackages/*
# except build/, which is used as an MSBuild target.
!**/[Pp]ackages/build/
```

(which are not some fantasy rules but part of the [`.gitignore` standard for VisualStudio/C#](https://github.com/github/gitignore/blob/cdd9e946da421758c6f42c427c7bc65c8326155d/VisualStudio.gitignore#L199-L202))

Query:

```js
walk.sync()
```

Expected output:

```js
[ '.ignore', 'foo.txt' ]
```

Actual output:

```js
[ '.ignore', 'bin/some.thing', 'foo.txt' ]
```

Quoting the [gitignore docs](http://git-scm.com/docs/gitignore#_pattern_format) (emphasis mine):

> An optional prefix `!` which negates the pattern; *any matching file excluded by a previous pattern will become included again.* It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. Put a backslash (`\`) in front of the first `!` for patterns that begin with a literal `!`, for example, `\!important!.txt`.

Unless defined in these docs, ignore-walks will include every file that does match the non-negated pattern unconditionally:

https://github.com/npm/ignore-walk/blob/9291ce1e30cecadb31f446e94b14578e6bfb7eca/index.js#L240

**Comment by wraithgar** [comment]
Fixed by https://github.com/npm/ignore-walk/pull/116
